server:
  port: 80

eureka: 
  client:
    register-with-eureka: false # 不在eureka中进行注册
    service-url:
      defaultZone: http://edmin:hello@eureka-7001.com:7001/eureka,http://edmin:hello@eureka-7002.com:7002/eureka,http://edmin:hello@eureka-7003.com:7003/eureka
  instance:
    instance-id: consumer-80.com
    prefer-ip-address: true   # 底部显示IP地址