spring:
  application:
   name: myspringcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/dept8001   # 数据库连接地址
    username: root                                  # 数据库用户名
    password: mysqladmin                            # 数据库连接密码
    dbcp2:    
      min-idle: 1                                  # 数据库连接池的最小维持连接数    
      max-idle: 1                                  # 数据库连接池的最大维持连接数    
      initial-size: 1                               # 初始化提供的连接数
      max-total: 1                                  # 最大的连接数
      max-wait-millis: 200                          # 连接超时时间 
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
  type-aliases-package: cn.lh.MySpringCloud.api.vo     # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
server:
  port: 8003              #微服务的端口
  
eureka:
  client:
    service-url:
      defaultZone: http://edmin:hello@eureka-7001.com:7001/eureka,http://edmin:hello@eureka-7002.com:7002/eureka,http://edmin:hello@eureka-7003.com:7003/eureka   # 定义你服务的注册路径
  instance:
    instance-id: dept-8003.com
    prefer-ip-address: true   # 底部显示IP地址
      
info:
  app.name: lh-springcloud-dept
  company.name: www.github.lh124
  build.artifactId: $project.artifactId$
  build.version: $project.version$
#security:
#  sessions: always    #总是保持session状态，session状态不会变
#  sessions: stateless  #不保留用户的状态，每一次请求都是一个新的用户 ，
#  basic:
#    enabled: true       #启动springSecurity的安全配置， 默认为ture
#  user:
#    name: lh      #用户名
#    password: liaohuan  #密码