server:
  port: 7001      # Eureka服务端口
security:
  basic:
    enabled: true
  user:
    name: edmin
    password: hello


eureka: 
  client:
    service-url:
      defaultZone: http://edmin:hello@eureka-7002.com:7002/eureka,http://edmin:hello@eureka-7003.com:7003/eureka
    register-with-eureka: false     # 当前的服务不注册到eureka之中
    fetch-registry: false           # 该服务不通过eureka抓取任何注册信息
  instance: 
#    lease-renewal-interval-in-seconds: 30    # 设置心跳的间隔时间（30秒）
#    lease-expiration-duration-in-seconds: 90  # 设置心跳超过了的时间 
    hostname: eureka-7001.com
#  server:
#    eviction-interval-timer-in-ms:  10000  # 设置无效服务的清理时间（默认是60秒）
#    enable-self-preservation: false     # 关闭受保护模式

